# Generated by Django 4.1.7 on 2023-04-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='food/', verbose_name='image'),
        ),
    ]
