# Generated by Django 4.1.7 on 2023-03-23 12:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0003_сart_favorites_сart_уже в корзине_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Сart',
            new_name='ShoppingBasker',
        ),
    ]
