# Generated by Django 4.1.7 on 2023-03-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_alter_favorites_recipe_alter_favorites_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='amount',
            field=models.SmallIntegerField(default=1, verbose_name='колтичество'),
        ),
    ]
