# Generated by Django 4.1.7 on 2023-03-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_alter_foodrecipe_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='food.food', verbose_name='ингредиенты'),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='food.recipe', verbose_name='рецепт'),
        ),
    ]
