# Generated by Django 4.1.7 on 2023-03-30 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0008_alter_foodrecipe_food_alter_foodrecipe_recipe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingBasker',
            new_name='ShoppingBasket',
        ),
        migrations.AlterField(
            model_name='tagrecipe',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagr', to='food.recipe', verbose_name='рецепт'),
        ),
        migrations.AlterField(
            model_name='tagrecipe',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagr', to='food.tag', verbose_name='тэг'),
        ),
    ]
